// ------------------------------------------ LOCAL HOST ------------------------------------------

// GUEST COLLECTION

###
GET http://localhost:8080/guest

###
GET http://localhost:8080/guest/6556d6b9e506d9ba191f68da

###
POST http://localhost:8080/guest/ HTTP/1.1
content-type: application/json

{
    "guestID": "5782",
    "firstName": "Darvin",
    "lastName": "Brown",
    "email": "mynameisdarvin@fake.com",
    "phone": "021-873-0840",
    "address": "fake address 777",
    "dateOfBirth": "11/25/1989",
    "identificationConfirmation": "State ID"
}

###
PUT http://localhost:8080/guest/655570fe4f93dd1059559c60 HTTP/1.1
content-type: application/json

{
    "guestID": "9654",
    "firstName": "Mike",
    "lastName": "Santos",
    "email": "mikesantos@fake.com",
    "phone": "000-333-0000",
    "address": "fake address 321",
    "dateOfBirth": "11/25/1989",
    "identificationConfirmation": "Driver License"
}

###
DELETE http://localhost:8080/guest/6556d6b9e506d9ba191f68da HTTP/1.1

// RESERVATIONS COLLECTION

###
GET http://localhost:8080/reservations

###
GET http://localhost:8080/reservations/###

###
POST http://localhost:8080/reservations HTTP/1.1
content-type: application/json

###
PUT http://localhost:8080/reservations/### HTTP/1.1
content-type: application/json

###
DELETE http://localhost:8080/reservations/### HTTP/1.1

// ROOMS COLLECTION
###
GET http://localhost:8080/rooms

###
GET http://localhost:8080/rooms/65544948809415b9b22fee1b

### create Rooms
POST http://localhost:8080/rooms HTTP/1.1
content-type: application/json

{
    "roomNumber": "3002",
    "description": "Indulge in the epitome of luxury with our Deluxe Suite. This spacious and elegantly appointed suite is designed to offer a premium experience for our discerning guests.",
    "features": "Panoramic City Views, Private Balcony, Spa-Inspired Bathroom, Complimentary Minibar",
    "pricePerNight": "$1000",
    "roomType": "Deluxe Suite",
    "status": "Booked"
}


### update Room with roomId
PUT http://localhost:8080/rooms/65584df2394c88cf838197d0 HTTP/1.1
content-type: application/json

{
    "roomNumber": "3002",
    "description": "Indulge in the epitome of luxury with our Deluxe Suite. This spacious and elegantly appointed suite is designed to offer a premium experience for our discerning guests.",
    "features": "Panoramic City Views, Private Balcony, Spa-Inspired Bathroom, Complimentary Minibar",
    "pricePerNight": "$3000",
    "roomType": "Deluxe Suite",
    "status": "Booked"
}

###
DELETE http://localhost:8080/rooms/65584f906623e93b34867e98 HTTP/1.1

// SERVICES COLLECTION

###
GET http://localhost:8080/services

###
GET http://localhost:8080/services/###

###
POST http://localhost:8080/services HTTP/1.1
content-type: application/json

###
PUT http://localhost:8080/services/### HTTP/1.1
content-type: application/json

###
DELETE http://localhost:8080/services/### HTTP/1.1

// STAFF COLLECTION

###
GET http://localhost:8080/staff

###
GET http://localhost:8080/staff/###

###
POST http://localhost:8080/staff HTTP/1.1
content-type: application/json

###
PUT http://localhost:8080/staff/### HTTP/1.1
content-type: application/json

###
DELETE http://localhost:8080/staff/### HTTP/1.1





// ------------------------------------------ RENDER LINKS ------------------------------------------

###
GET https://hotel-transylvania.onrender.com/guest

###
GET https://hotel-transylvania.onrender.com/guest/65543ec10b9769dd0c74f4e2

###
POST https://hotel-transylvania.onrender.com/guest HTTP/1.1
content-type: application/json

###
PUT https://hotel-transylvania.onrender.com/guest/### HTTP/1.1
content-type: application/json

###
DELETE https://hotel-transylvania.onrender.com/guest/### HTTP/1.1

// RESERVATIONS COLLECTION

###
GET https://hotel-transylvania.onrender.com/reservations

###
GET https://hotel-transylvania.onrender.com/reservations/###

###
POST https://hotel-transylvania.onrender.com/reservations HTTP/1.1
content-type: application/json

###
PUT https://hotel-transylvania.onrender.com/reservations/### HTTP/1.1
content-type: application/json

###
DELETE https://hotel-transylvania.onrender.com/reservations/### HTTP/1.1

// ROOMS COLLECTION
###
GET https://hotel-transylvania.onrender.com/rooms

###
GET https://hotel-transylvania.onrender.com/rooms/###

###
POST https://hotel-transylvania.onrender.com/rooms HTTP/1.1
content-type:application/json

###
PUT https://hotel-transylvania.onrender.com/rooms/### HTTP/1.1
content-type: application/json

###
DELETE https://hotel-transylvania.onrender.com/rooms/### HTTP/1.1

// SERVICES COLLECTION

###
GET https://hotel-transylvania.onrender.com/services

###
GET https://hotel-transylvania.onrender.com/services/###

###
POST https://hotel-transylvania.onrender.com/services HTTP/1.1
content-type: application/json

###
PUT https://hotel-transylvania.onrender.com/services/### HTTP/1.1
content-type: application/json

###
DELETE https://hotel-transylvania.onrender.com/services/### HTTP/1.1

// STAFF COLLECTION

###
GET https://hotel-transylvania.onrender.com/staff

###
GET https://hotel-transylvania.onrender.com/staff/###

###
POST https://hotel-transylvania.onrender.com/staff HTTP/1.1
content-type: application/json

###
PUT https://hotel-transylvania.onrender.com/staff/### HTTP/1.1
content-type: application/json

###
DELETE https://hotel-transylvania.onrender.com/staff/### HTTP/1.1